baseURL: https://echq.org.uk/
languageCode: en-gb
title: EMF Communications Headquarters

theme: hextra

menu:
  main:
    - identifier: 2026planning
      name: 2026 Planning
      pageRef: /2026
      weight: 1

params:
  footer:
    enable: false
  navbar:
    displayTitle: true
    displayLogo: true
    logo:
      path: images/echq-compact.png
      link: /
      width: 40
      height: 20
  editURL:
    enable: true
    base: "https://github.com/EMF-hams/echq-website/edit/main/content/"
  page:
    width: wide

markup:
  goldmark:
    renderer:
      unsafe: true
