baseURL: https://echq.org.uk/
languageCode: en-gb
title: EMF Communications Headquarters

theme: hextra

menu:
  main:
    - identifier: wiki
      name: Wiki
      pageRef: /docs
      weight: 1

params:
  footer:
    enable: false
  navbar:
    displayTitle: true
    displayLogo: true
    logo:
      path: images/echq-compact.png
      link: /
      width: 40
      height: 20

markup:
  goldmark:
    renderer:
      unsafe: true
